name: Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      terraform_code:
        description: 'Terraform code to run'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.SA_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create main.tf from input
        run: printf "%s" "${{ github.event.inputs.terraform_code }}" > main.tf

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform Code
        run: terraform validate

      - name: Apply Terraform Configuration
        run: terraform apply -auto-approve
